import { Job, Category } from "./types";

export const CATEGORIES: Category[] = [
  { id: "developer-software", name: "Developer / Software Eng.", icon: "Code", count: 42 },
  { id: "copywriting-content", name: "Copywriting / Content", icon: "PenTool", count: 12 },
  { id: "design-creative", name: "Design / Creative", icon: "Palette", count: 28 },
  { id: "marketing-product", name: "Marketing / Product", icon: "TrendingUp", count: 19 },
  { id: "data-science", name: "Data Science & Analytics", icon: "BarChart3", count: 15 },
  { id: "customer-success", name: "Customer Success / HR", icon: "Users", count: 8 },
  { id: "product-management", name: "Product Management", icon: "Sliders", count: 14 },
  { id: "academic-tutors", name: "Academic / Tutors", icon: "GraduationCap", count: 6 },
];

export const INITIAL_JOBS: Job[] = [
  // ==================== DEVELOPER / SOFTWARE ENG (10 jobs to trigger horizontal scroll!) ====================
  {
    id: "dev-1",
    title: "Senior Full Stack Engineer",
    company: "Vercel",
    logoBg: "bg-black text-white",
    location: "Remote, US",
    type: "Full-time",
    salary: "$165k - $190k",
    description: "Build the future of the web. Collaborate with designers and product managers to improve developer experience globally with modern React and Next.js APIs.",
    postedTime: "Posted 2 hours ago",
    category: "developer-software",
    applicants: 24,
    experienceLevel: "Senior",
  },
  {
    id: "dev-2",
    title: "Core Infrastructure Engineer",
    company: "Supabase",
    logoBg: "bg-emerald-950 text-emerald-400",
    location: "Remote, Global",
    type: "Contract",
    salary: "Custom Rate / hr",
    description: "Scale open-source PostgreSQL services. Optimize real-time data replication systems, manage connection pooling, and ship robust backend modules written in Go and Rust.",
    postedTime: "Posted 1 day ago",
    category: "developer-software",
    applicants: 15,
    experienceLevel: "Senior",
  },
  {
    id: "dev-3",
    title: "Frontend UI Developer",
    company: "Linear",
    logoBg: "bg-indigo-950 text-indigo-300",
    location: "Remote, Europe",
    type: "Full-time",
    salary: "$120k - $145k",
    description: "Craft highly performant, sub-100ms keyboard-driven web applications. You have an eye for pristine animations, perfect typographic alignments, and deep state-management optimizations.",
    postedTime: "Posted 3 days ago",
    category: "developer-software",
    applicants: 41,
    experienceLevel: "Mid",
  },
  {
    id: "dev-4",
    title: "React Native Mobile Dev",
    company: "Stripe",
    logoBg: "bg-blue-600 text-white",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: "$150k - $175k",
    description: "Bring Stripe's payment dashboard utilities to iOS and Android devices. Optimize biometric logins, high-frequency chart rendering, and transaction flows locally.",
    postedTime: "Posted 4 days ago",
    category: "developer-software",
    applicants: 19,
    experienceLevel: "Mid",
  },
  {
    id: "dev-5",
    title: "Junior Backend Engineer",
    company: "Railway",
    logoBg: "bg-pink-600 text-white",
    location: "Remote, US",
    type: "Full-time",
    salary: "$85k - $105k",
    description: "Support our core cloud hosting orchestration platform. Learn and scale container isolation patterns, build user-friendly CLI integrations, and monitor metrics databases.",
    postedTime: "Posted 5 days ago",
    category: "developer-software",
    applicants: 89,
    experienceLevel: "Junior",
  },
  {
    id: "dev-6",
    title: "DevOps & Platform Architect",
    company: "HashiCorp",
    logoBg: "bg-purple-900 text-purple-200",
    location: "Austin, TX / Hybrid",
    type: "Full-time",
    salary: "$180k - $210k",
    description: "Design robust build workflows and multi-cloud infrastructure environments. Secure production systems using state-of-the-art policy engines, Terraform, and Vault cluster setups.",
    postedTime: "Posted 1 week ago",
    category: "developer-software",
    applicants: 8,
    experienceLevel: "Senior",
  },
  {
    id: "dev-7",
    title: "iOS Swift Developer",
    company: "Apple",
    logoBg: "bg-slate-800 text-slate-100",
    location: "Cupertino, CA",
    type: "Full-time",
    salary: "$170k - $200k",
    description: "Implement interactive new features in standard system apps. Maintain high compliance protocols, create delightful visual layouts using SwiftUI frameworks, and optimize memory leaks.",
    postedTime: "Posted 1 week ago",
    category: "developer-software",
    applicants: 37,
    experienceLevel: "Senior",
  },
  {
    id: "dev-8",
    title: "Developer Advocate",
    company: "Clerk",
    logoBg: "bg-sky-950 text-sky-450",
    location: "Remote, US & EU",
    type: "Full-time",
    salary: "$130k - $155k",
    description: "Empower developer communities with modern authentication guidelines. Write highly readable code tutorials, maintain open-source examples, and speak at web workshops.",
    postedTime: "Posted 1 week ago",
    category: "developer-software",
    applicants: 54,
    experienceLevel: "Mid",
  },
  {
    id: "dev-9",
    title: "Rust compiler Specialist",
    company: "Figma",
    logoBg: "bg-amber-600 text-white",
    location: "San Francisco, CA",
    type: "Contract",
    salary: "$150/hr - $180/hr",
    description: "Help speed up Figma’s WebAssembly graphics engine runtime. You will work on low-level binary compilers, compiler flags, and memory layout schemes to enhance collaboration performance.",
    postedTime: "Posted 2 weeks ago",
    category: "developer-software",
    applicants: 11,
    experienceLevel: "Senior",
  },
  {
    id: "dev-10",
    title: "Site Reliability Engineer",
    company: "Slack",
    logoBg: "bg-teal-700 text-teal-100",
    location: "Vancouver, Canada",
    type: "Full-time",
    salary: "$140k - $160k",
    description: "Prevent outages and manage high-load concurrent server communication loops, microservice backbones, and logging metrics pipelines for over 20 million users.",
    postedTime: "Posted 2 weeks ago",
    category: "developer-software",
    applicants: 12,
    experienceLevel: "Mid",
  },

  // ==================== DESIGN / CREATIVE (9 jobs to trigger horizontal scroll!) ====================
  {
    id: "dst-1",
    title: "Principal Product Designer",
    company: "Figma",
    logoBg: "bg-rose-500 text-white",
    location: "Remote, US",
    type: "Full-time",
    salary: "$180k - $210k",
    description: "Formulate the future workflows of Figma's collaboration canvas. Shape next-generation styling, auto-layouts, and prototyping interactions globally.",
    postedTime: "Posted 4 hours ago",
    category: "design-creative",
    applicants: 31,
    experienceLevel: "Senior",
  },
  {
    id: "dst-2",
    title: "Senior Brand Designer",
    company: "Airbnb",
    logoBg: "bg-rose-600 text-white",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: "$140k - $165k",
    description: "Direct offline and online visual branding pipelines. Design highly cinematic web landing campaigns, beautiful iconography patterns, and modern marketing brand books.",
    postedTime: "Posted 1 day ago",
    category: "design-creative",
    applicants: 18,
    experienceLevel: "Senior",
  },
  {
    id: "dst-3",
    title: "Junior UI/UX Designer",
    company: "Framer",
    logoBg: "bg-blue-500 text-white",
    location: "Amsterdam, NL / Hybrid",
    type: "Full-time",
    salary: "€65k - €75k",
    description: "Collaborate closely with content designers and frontend teams. Deliver delightful mockups, build custom responsive layouts inside our tools, and gather platform feedback.",
    postedTime: "Posted 2 days ago",
    category: "design-creative",
    applicants: 154,
    experienceLevel: "Junior",
  },
  {
    id: "dst-4",
    title: "Motion Graphics Designer",
    company: "Duolingo",
    logoBg: "bg-lime-500 text-lime-950",
    location: "Pittsburgh, PA",
    type: "Full-time",
    salary: "$95k - $120k",
    description: "Bring Duo the owl and standard screen interface elements to life with colorful, engaging vector motion graphics, cute keyframe loops, and reward fireworks.",
    postedTime: "Posted 3 days ago",
    category: "design-creative",
    applicants: 45,
    experienceLevel: "Mid",
  },
  {
    id: "dst-5",
    title: "Web Illustrative Artist",
    company: "Mailchimp",
    logoBg: "bg-yellow-400 text-black",
    location: "Remote, US-East",
    type: "Contract",
    salary: "$80 - $110/hr",
    description: "Draw organic-style brand assets and landing illustrations. You will help bring a friendly, warm voice to hundreds of email marketing and campaign page themes.",
    postedTime: "Posted 5 days ago",
    category: "design-creative",
    applicants: 29,
    experienceLevel: "Mid",
  },
  {
    id: "dst-6",
    title: "Senior Design Systems Architect",
    company: "Loom",
    logoBg: "bg-purple-600 text-white",
    location: "Remote, US",
    type: "Full-time",
    salary: "$155k - $185k",
    description: "Define consistent interactive standards for video recorders, sharing links, and enterprise folders. Maintain high level accessibility compliance catalogs.",
    postedTime: "Posted 6 days ago",
    category: "design-creative",
    applicants: 22,
    experienceLevel: "Senior",
  },
  {
    id: "dst-7",
    title: "Product Design Prototyper",
    company: "Retool",
    logoBg: "bg-amber-700 text-amber-50",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: "$130k - $160k",
    description: "Build interactive canvas prototypes with complex high-fidelity drag behavior, dynamic data lists, and integrated settings sidebars.",
    postedTime: "Posted 1 week ago",
    category: "design-creative",
    applicants: 14,
    experienceLevel: "Mid",
  },
  {
    id: "dst-8",
    title: "Visual Designer (Contract)",
    company: "Vercel",
    logoBg: "bg-black text-white",
    location: "Remote, Global",
    type: "Contract",
    salary: "$90/hr",
    description: "Partner with developer relations to design gorgeous conference sliders, landing assets, merchandise packages, and graphical social banners.",
    postedTime: "Posted 1 week ago",
    category: "design-creative",
    applicants: 76,
    experienceLevel: "Mid",
  },
  {
    id: "dst-9",
    title: "XR Spatial Interface Designer",
    company: "Meta",
    logoBg: "bg-blue-900 text-white",
    location: "Menlo Park, CA",
    type: "Full-time",
    salary: "$195k - $225k",
    description: "Define boundaries of spatial and hand-tracking interactive UIs inside headsets. Perfect 3D volumetric layout scales, physical buttons, and visual overlays.",
    postedTime: "Posted 2 weeks ago",
    category: "design-creative",
    applicants: 9,
    experienceLevel: "Senior",
  },

  // ==================== COPYWRITING / CONTENT (4 jobs) ====================
  {
    id: "cpy-1",
    title: "Senior UX Writer & Content Strategist",
    company: "Slack",
    logoBg: "bg-purple-800 text-white",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: "$125k - $150k",
    description: "Craft simple, delightful, and human-sounding microcopy. Lead taxonomy definitions, context tooltips, help center templates, and transactional emails.",
    postedTime: "Posted 1 day ago",
    category: "copywriting-content",
    applicants: 12,
    experienceLevel: "Senior",
  },
  {
    id: "cpy-2",
    title: "Technical Documentation Copywriter",
    company: "Supabase",
    logoBg: "bg-emerald-950 text-emerald-300",
    location: "Remote, EU",
    type: "Full-time",
    salary: "$95k - $115k",
    description: "Convert high-complexity infrastructure engineering specifications into clean, accessible manuals. Provide clear setup prompts for storage and cloud server tools.",
    postedTime: "Posted 3 days ago",
    category: "copywriting-content",
    applicants: 31,
    experienceLevel: "Mid",
  },
  {
    id: "cpy-3",
    title: "AI Prompt & Copy Tutor",
    company: "Anthropic",
    logoBg: "bg-amber-800 text-white",
    location: "San Francisco / Hybrid",
    type: "Contract",
    salary: "$70 - $95 / hr",
    description: "Write rigorous evaluation prompts and creative copy tests to challenge model generation outputs. Refine linguistic flows, and evaluate natural expression parameters.",
    postedTime: "Posted 5 days ago",
    category: "copywriting-content",
    applicants: 142,
    experienceLevel: "Junior",
  },
  {
    id: "cpy-4",
    title: "Marketing Copywriter",
    company: "Notion",
    logoBg: "bg-stone-900 text-white",
    location: "Remote, US",
    type: "Full-time",
    salary: "$110k - $130k",
    description: "Generate high-converting newsletters, product-launch descriptions, and feature brochures. Help share the visual story of Notion's workplace utilities.",
    postedTime: "Posted 1 week ago",
    category: "copywriting-content",
    applicants: 89,
    experienceLevel: "Mid",
  },

  // ==================== MARKETING / PRODUCT (5 jobs) ====================
  {
    id: "mkt-1",
    title: "Director of Product Marketing",
    company: "Stripe",
    logoBg: "bg-indigo-600 text-white",
    location: "New York, NY",
    type: "Full-time",
    salary: "$190k - $220k",
    description: "Own the launch pipeline for digital transaction portals and financial tools. Align market campaigns with sales materials and developer guidelines.",
    postedTime: "Posted 8 hours ago",
    category: "marketing-product",
    applicants: 16,
    experienceLevel: "Senior",
  },
  {
    id: "mkt-2",
    title: "Digital Growth Marketer",
    company: "Mercury",
    logoBg: "bg-emerald-850 text-emerald-100",
    location: "Remote, US",
    type: "Full-time",
    salary: "$110k - $135k",
    description: "Scale organic growth, user acquisition, and corporate referrals dashboard funnels. Evaluate high-performing metrics, and optimize multi-channel budgets.",
    postedTime: "Posted 2 days ago",
    category: "marketing-product",
    applicants: 42,
    experienceLevel: "Mid",
  },
  {
    id: "mkt-3",
    title: "Junior Social Content Producer",
    company: "Duolingo",
    logoBg: "bg-lime-500 text-lime-980",
    location: "New York, NY",
    type: "Full-time",
    salary: "$75k - $90k",
    description: "Help make educational programs go viral on tech networks. Produce interactive humor feeds, schedule daily content streams, and interact with visual creators.",
    postedTime: "Posted 4 days ago",
    category: "marketing-product",
    applicants: 210,
    experienceLevel: "Junior",
  },
  {
    id: "mkt-4",
    title: "SEO Strategy Analyst",
    company: "Zapier",
    logoBg: "bg-orange-600 text-white",
    location: "Remote, Global",
    type: "Full-time",
    salary: "$100k - $125k",
    description: "Diagnose crawl bugs, perform rich keyword searches, and build massive programmatic landing campaigns for zero-code dynamic workflows.",
    postedTime: "Posted 1 week ago",
    category: "marketing-product",
    applicants: 35,
    experienceLevel: "Mid",
  },
  {
    id: "mkt-5",
    title: "Community Program Manager",
    company: "Webflow",
    logoBg: "bg-blue-600 text-white",
    location: "London, UK / Hybrid",
    type: "Full-time",
    salary: "£75k - £95k",
    description: "Launch global designer group programs. Schedule high-level events, address forum suggestions, and empower independent freelancers.",
    postedTime: "Posted 1 week ago",
    category: "marketing-product",
    applicants: 44,
    experienceLevel: "Mid",
  },

  // ==================== DATA SCIENCE & ANALYTICS (3 jobs) ====================
  {
    id: "dat-1",
    title: "Lead Data Scientist",
    company: "Netflix",
    logoBg: "bg-red-650 text-white",
    location: "Los Gatos, CA",
    type: "Full-time",
    salary: "$210k - $250k",
    description: "Lead recommendation scoring, real-time user-graph calculations, and server load modeling parameters using PyTorch and customized cloud systems.",
    postedTime: "Posted 12 hours ago",
    category: "data-science",
    applicants: 19,
    experienceLevel: "Senior",
  },
  {
    id: "dat-2",
    title: "Quantitative Analytics Specialist",
    company: "Coinbase",
    logoBg: "bg-blue-600 text-white",
    location: "Remote, US",
    type: "Full-time",
    salary: "$160k - $185k",
    description: "Model risk patterns, digital ledger anomaly thresholds, and liquidity queues for secure instant cryptofinance transactions globally.",
    postedTime: "Posted 2 days ago",
    category: "data-science",
    applicants: 28,
    experienceLevel: "Senior",
  },
  {
    id: "dat-3",
    title: "Data Analytics Associate",
    company: "Segment",
    logoBg: "bg-emerald-600 text-white",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: "$90k - $115k",
    description: "Create SQL dashboards to analyze click event sequences. Design cross-channel analytical funnels, and write automated Python metrics scripts.",
    postedTime: "Posted 5 days ago",
    category: "data-science",
    applicants: 76,
    experienceLevel: "Junior",
  },

  // ==================== CUSTOMER SUCCESS & HR (3 jobs) ====================
  {
    id: "hr-1",
    title: "Global Talent Acquisition Partner",
    company: "Figma",
    logoBg: "bg-rose-500 text-white",
    location: "Remote, US",
    type: "Full-time",
    salary: "$110k - $135k",
    description: "Hire world-class UX designers and graphics specialists. Drive equitable interviews, support candidate communications, and design offer structures.",
    postedTime: "Posted 1 day ago",
    category: "customer-success",
    applicants: 15,
    experienceLevel: "Mid",
  },
  {
    id: "hr-2",
    title: "Enterprise Success Manager",
    company: "Slack",
    logoBg: "bg-purple-800 text-white",
    location: "New York, NY",
    type: "Full-time",
    salary: "$130k - $150k",
    description: "Own growth relationships with Fortune 500 company tech heads. Educate teams on advanced communication integrations and productivity funnels.",
    postedTime: "Posted 3 days ago",
    category: "customer-success",
    applicants: 31,
    experienceLevel: "Senior",
  },
  {
    id: "hr-3",
    title: "Junior People Ops Associate",
    company: "Linear",
    logoBg: "bg-slate-900 text-white",
    location: "Helsinki, Finland",
    type: "Full-time",
    salary: "€45k - €55k",
    description: "Support international onboarding lists, manage insurance/pension forms, organize creative offsite meets, and update workplace manuals.",
    postedTime: "Posted 1 week ago",
    category: "customer-success",
    applicants: 18,
    experienceLevel: "Junior",
  },

  // ==================== PRODUCT MANAGEMENT (3 jobs) ====================
  {
    id: "pm-1",
    title: "Principal PM, AI Workflows",
    company: "Google",
    logoBg: "bg-red-100 text-red-700",
    location: "Mountain View, CA",
    type: "Full-time",
    salary: "$210k - $245k",
    description: "Formulate strategic roadmaps for large language model IDE integrations. Partner with engineers and prompt-design researchers to launch workspace tools.",
    postedTime: "Posted 2 days ago",
    category: "product-management",
    applicants: 45,
    experienceLevel: "Senior",
  },
  {
    id: "pm-2",
    title: "Senior Technical Product Manager",
    company: "Supabase",
    logoBg: "bg-emerald-950 text-emerald-300",
    location: "Remote, Global",
    type: "Full-time",
    salary: "$150k - $175k",
    description: "Drive features for multi-tenant database backup storage and edge function runtimes. Translate user demands into rigorous infrastructure tickets.",
    postedTime: "Posted 4 days ago",
    category: "product-management",
    applicants: 15,
    experienceLevel: "Senior",
  },
  {
    id: "pm-3",
    title: "Associate Product Manager",
    company: "Vercel",
    logoBg: "bg-black text-white",
    location: "San Francisco / Hybrid",
    type: "Full-time",
    salary: "$110k - $130k",
    description: "Coordinate visual analytics dashboards features. Organize user polls, refine widget specifications, and check weekly telemetry lists.",
    postedTime: "Posted 1 week ago",
    category: "product-management",
    applicants: 104,
    experienceLevel: "Junior",
  },

  // ==================== ACADEMIC / TUTORS (3 jobs) ====================
  {
    id: "acd-1",
    title: "Senior Computer Science Lecturer",
    company: "Stanford Online",
    logoBg: "bg-red-800 text-white",
    location: "Stanford, CA / Remote",
    type: "Part-time",
    salary: "$120/hr - $155/hr",
    description: "Teach post-graduate students modern web performance techniques, concurrent server setups, database indexes, and advanced TypeScript compilation.",
    postedTime: "Posted 3 days ago",
    category: "academic-tutors",
    applicants: 6,
    experienceLevel: "Senior",
  },
  {
    id: "acd-2",
    title: "UI Design Course Facilitator",
    company: "Shift Nudge",
    logoBg: "bg-purple-950 text-purple-300",
    location: "Remote, US & CA",
    type: "Contract",
    salary: "$80/hr",
    description: "Lead group portfolios evaluation video calls. Address typography pairings, spatial spacing guidelines, contrast checks, and responsive design systems.",
    postedTime: "Posted 1 week ago",
    category: "academic-tutors",
    applicants: 12,
    experienceLevel: "Mid",
  },
  {
    id: "acd-3",
    title: "Mathematics & Stats Coach",
    company: "Khan Academy",
    logoBg: "bg-green-700 text-white",
    location: "Remote, US",
    type: "Part-time",
    salary: "$45 - $60/hr",
    description: "Formulate interactive exercises for college-level probability paths. Help construct animated video graphics representing data structures.",
    postedTime: "Posted 1 week ago",
    category: "academic-tutors",
    applicants: 41,
    experienceLevel: "Junior",
  }
];
